### ISSUE TITLE
Alternative solution?

### ISSUE THREAD

**Issue by dimitry-ishenko** [peper0/qtasio#1]
In light of this:
http://www.qtcentre.org/threads/53229-How-to-integrate-asio-io_service-with-Qt-event-loop
have you been able to come up with an alternative solution?

Maybe there is a way to call `QApplication::processEvents` from the `asio::io_service`?

**Comment by peper0** [comment]
> Maybe there is a way to call `QApplication::processEvents` from the `asio::io_service`?

It is technically possible. You can just set a timer on `asio::io_service` and call `QApplication::processEvents` in this timer. But this solution is a bit dirty and has a practical drawback - you either introduce some lag to your software (if you call this timer not very frequently) or waste your cpu for frequent checking that there is nothing to do. But, I believe, in some cases such a solution is sufficient if you find reasonable trade off.

Of course you can also do it in the opposite way i.e. calling `io_service::poll()` from a Qt timer.

I was thinking about another solution involving additional thread. If we could split waiting for new "event" (timers or sockets) from handling them, we could have one thread that waits idle until there is something to do in Qt and whenever there is - make `io_service::post()` with `QApplication::processEvents`. However I'm not sure whether we could do it without changing the QT code.

**Comment by dimitry-ishenko** [comment]
I agree this is not the best solution. My train of thought was: let's say all GUI events get processed by Qt and all other events inside Asio. Calling `processEvents` every 10 - 20 ms should be sufficient to keep the GUI responsive and not waste too many CPU cycles.

But I like your idea with another thread. Can you post to io_service on another thread?

**Comment by peper0** [comment]
Yes, it's safe.

**Comment by dimitry-ishenko** [comment]
So maybe override `QCoreApplication::notify(QObject *receiver, QEvent *event)` and post `receiver->event(event)` to `io_service`. The only problem, is I don't think you can run the GUI loop on another thread...

**Comment by peper0** [comment]
I'm not sure whether all callbacks are forwarded through `QCoreApplication::notify`. Nevertheless, I think too that running Qt main loop in another thread isn't a good idea.
