### ISSUE TITLE
Nice job

### ISSUE THREAD

**Issue by vinipsmaker** [peper0/qtasio#2]
Hey, I'm working on integration between several event loops in a Boost.Asio-based project and I started with GLib. Eventually I'll move to Qt as well and I started to evaluate the options. I'll probably start from your code, but there are things I think I'll change. So I thought of pinging you to have an idea on the mindset you used to drive the implementation.

Let's start with an unusual but yet simple scenario before I throw the crazier idea at you: have you assumed `QAsioEventDispatcher` would/could be used in `QThread::setEventDispatcher()` (not `QCoreApplication::setEventDispatcher()`)? Would it be safe to use `QAsioEventDispatcher` in a process that creates no `QCoreApplication` (or maybe it does create just to set a few attributes such as application name and so on, but it never runs its event loop and otherwise only relies on `QThread` event loops)?

Now for something truly unusual: What are your thoughts on running the event loop in a [Boost.Asio strand](https://www.boost.org/doc/libs/1_75_0/doc/html/boost_asio/overview/core/strands.html)? The outcome is... every `QAsioEventDispatcher` would work as an actor. From its point of view, it's single-threaded. However it'd be “unscheduled” from the thread as soon as it is about to block on waiting for more events so it can free the thread to pick up another `QAsioEventDispatcher` from the pool. That's the design I'm using for the GLib integration and I'd like to use it for the Qt integration (and other future integrations) as well.

**Comment by peper0** [comment]
Sorry for the late answer.
I wrote this code long time ago and I've not used it for a few years, so I don't remember too much. Therefore, I'm sorry to say that I cannot answer your questions.
I hope your solution will be successfull :) Good luck!

**Comment by vinipsmaker** [comment]
> Therefore, I'm sorry to say that I cannot answer your questions.

That's okay. I'll read it anyway after I'm done with my current task on integrating glib.

Thanks for your work.
